apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::729627741573:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-dJQWetPQ0MYx
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-29T08:50:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2721"
  uid: 53dbe1c6-af26-4fd3-8f5a-505c0345442a
